version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: developer_app
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - ./backend/baza.sql:/docker-entrypoint-initdb.d/baza.sql:ro # Make the SQL file read-only
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: devuser
      PMA_PASSWORD: devpass
    ports:
      - "8080:80"
    depends_on:
      - mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html:cached # Optimize file sync with the host
      - ./msmtp.log:/var/log/msmtp.log # Log for email debugging
    depends_on:
      - mysql

volumes:
  mysql_data:
